// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderHub.Infrastructure.Persistence;

#nullable disable

namespace ProviderHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProviderHubDbContext))]
    [Migration("20260906231851_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProviderHub.Domain.Providers.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("ProviderHub.Domain.Providers.ServiceOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ProviderId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceOfferings_Provider_Service");

                    b.ToTable("ServiceOfferings", (string)null);
                });

            modelBuilder.Entity("ProviderHub.Domain.Services.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Services_Name");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("ProviderHub.Domain.Providers.Provider", b =>
                {
                    b.OwnsOne("ProviderHub.Domain.Common.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("ProviderId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ProviderId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Providers_Email");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.OwnsOne("ProviderHub.Domain.Common.ValueObjects.WebsiteUrl", "Website", b1 =>
                        {
                            b1.Property<int>("ProviderId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)")
                                .HasColumnName("Website");

                            b1.HasKey("ProviderId");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.OwnsOne("ProviderHub.Domain.Providers.ValueObjects.Nit", "Nit", b1 =>
                        {
                            b1.Property<int>("ProviderId")
                                .HasColumnType("int");

                            b1.Property<string>("BaseNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("NitBaseNumber");

                            b1.Property<byte>("CheckDigit")
                                .HasColumnType("tinyint")
                                .HasColumnName("NitCheckDigit");

                            b1.HasKey("ProviderId");

                            b1.HasIndex("BaseNumber")
                                .IsUnique()
                                .HasDatabaseName("UX_Providers_Nit");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nit")
                        .IsRequired();

                    b.Navigation("Website")
                        .IsRequired();
                });

            modelBuilder.Entity("ProviderHub.Domain.Providers.ServiceOffering", b =>
                {
                    b.HasOne("ProviderHub.Domain.Providers.Provider", null)
                        .WithMany("Offerings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProviderHub.Domain.Services.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ProviderHub.Domain.Common.ValueObjects.CountryCode", "Countries", b1 =>
                        {
                            b1.Property<int>("ServiceOfferingId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("char(2)")
                                .HasColumnName("CountryCode");

                            b1.HasKey("ServiceOfferingId", "Value");

                            b1.ToTable("ServiceOfferingCountries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOfferingId");
                        });

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("ProviderHub.Domain.Services.Service", b =>
                {
                    b.OwnsOne("ProviderHub.Domain.Common.ValueObjects.Money", "HourlyRate", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("HourlyRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("HourlyRateCurrency");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("HourlyRate")
                        .IsRequired();
                });

            modelBuilder.Entity("ProviderHub.Domain.Providers.Provider", b =>
                {
                    b.Navigation("Offerings");
                });
#pragma warning restore 612, 618
        }
    }
}
